name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup
      run: sudo apt-get install build-essential
    - name: install
      run: sudo apt-get -y install libgtk-4-dev
    - name: make
      run: make
    - name: make check
      run: make check
